FROM ubuntu:20.04

# install requirements for downloading and adding the APT key
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y wget apt-transport-https gnupg

# Get intevations apt key
RUN wget -O - https://ssl.intevation.de/Intevation-Distribution-Key-2021.asc | apt-key add -

RUN echo "deb https://apt.intevation.de focal intelmq-testing" >> /etc/apt/sources.list

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y intelmq-mailgen
