FROM ubuntu:20.04

COPY common/setup-apt.sh /opt/
RUN /opt/setup-apt.sh intevation

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y intelmq-mailgen

# Install configuration
COPY mailgen/intelmq-mailgen.conf /etc/intelmq/intelmq-mailgen.conf
RUN mkdir -p /etc/intelmq/mailgen/templates
RUN mkdir -p /etc/intelmq/mailgen/formats

CMD ["bash", "/opt/init/run.sh"]
