version: "3"
services:
    intelmq:
        image: intelmq-full-pkg
        build:
            context: .
            dockerfile: intelmq/Dockerfile.full-pkg
    fody:
        image: intelmq-fody-full-pkg
        build:
            context: .
            dockerfile: fody/Dockerfile.full-pkg
    fody-backend:
        image: intelmq-fody-backend-full-pkg
        build:
            context: .
            dockerfile: fody-backend/Dockerfile.pkg
    database:
        image: intelmq-database-full-pkg
        build:
            context: .
            dockerfile: database/Dockerfile.full-pkg
    mailgen:
        image: intelmq-mailgen-full-pkg
        build:
            context: .
            dockerfile: mailgen/Dockerfile.full-pkg
    webinput-csv:
        image: intelmq-webinput-csv-full-pkg
        build:
            context: .
            dockerfile: webinput-csv/Dockerfile.full-pkg
    webinput-csv-backend:
        image: intelmq-fody-backend-full-pkg
        build:
            context: .
            dockerfile: webinput-csv-backend/Dockerfile.pkg
