version: "3"
services:
    intelmq:
        ports:
            - 1380:80
            - 1381:81
    fody-backend:
        ports:
            - 1340:8002
        volumes: 
            - $DEV_FODY_BACKEND_SRC:/opt/intelmq-fody-backend
    fody:
        ports:
            - 1382:8080
        volumes: 
            - $DEV_FODY_SRC:/opt/src/intelmq-fody
    webinput-csv-backend:
        ports:
            - 1341:8002
        volumes:
            - $DEV_WEBINPUT_CSV_BACKEND_SRC:/opt/intelmq-webinput-csv-backend
    webinput-csv:
        ports:
            - 1383:8080
        volumes:
            - $DEV_WEBINPUT_CSV_SRC:/opt/src/intelmq-webinput-csv/client