version: "3"
services:
    intelmq-full:
        image: intelmq-full
        container_name: intelmq-full
        build:
            context: .
            dockerfile: full-pkg/Dockerfile
            args:
                USE_CERTBUND: $USE_CERTBUND
        ports:
            - 1481:8000
            - 1480:80
        volumes:
            - $DEV_CERTBUND_RULES:/opt/rules
            - $DEV_CERTBUND_FORMATS:/opt/formats
            - $DEV_CERTBUND_TEMPLATES:/opt/templates
        restart: always
        networks: 
            - intelmq
    intelmq:
        image: intelmq-manager-full-pkg
        build:
            context: .
            dockerfile: intelmq/Dockerfile.full-pkg
        entrypoint: ["echo", "Service disabled."]
        restart: "no"
    fody:
        image: intelmq-fody-pkg
        build:
            context: .
            dockerfile: fody/Dockerfile.full-pkg
        entrypoint: ["echo", "Service disabled."]
        restart: "no"
    fody-backend:
        image: intelmq-fody-backend-pkg
        build:
            context: .
            dockerfile: fody-backend/Dockerfile.pkg
        entrypoint: ["echo", "Service disabled."]
        restart: "no"
    webinput-csv:
        image: intelmq-webinput-csv-spa-pkg
        build:
            context: .
            dockerfile: webinput-csv/Dockerfile.full-pkg
        entrypoint: ["echo", "Service disabled."]
        restart: "no"
    webinput-csv-backend:
        image: intelmq-fody-backend-pkg
        build:
            context: .
            dockerfile: webinput-csv-backend/Dockerfile.pkg
        entrypoint: ["echo", "Service disabled."]
        restart: "no"