version: "3"
services:
    intelmq:
        ports:
            - 1380:80
            - 1381:81
    fody-backend:
        # volumes: 
        #     - ${FODY_BACKEND_SRC}:/opt/intelmq-fody-backend
        ports:
            - 1340:8002
        build:
            args:
                REVISION: "master"
    fody:
        # volumes:
        #     - ${FODY_SRC}:/opt/src/intelmq-fody
        ports:
            - 1382:8080
        build:
            args:
                REVISION: "master"
    webinput-csv-backend:
        # volumes:
        #     - ${WEBINPUT_CSV_BACKEND_SRC}:/opt/intelmq-webinput-csv
        ports:
            - 1341:8002
        build:
            args:
                REVISION: "master"
    webinput-csv:
        # volumes:
        #     - ${WEBINPUT_CSV_SRC}:/opt/src/intelmq-webinput-csv
        ports:
            - 1383:8080
        build:
            args:
                REVISION: "master"
