#Github Workflow to find and notify about misspellings
#
#SPDX-FileCopyrightText: 2023 Intevation GmbH
#SPDX-License-Identifier: AGPL-3.0-or-later

name: "Codespell spelling check"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codespell:
    name: Find and notify about common misspellings
    runs-on: ubuntu-22.04
    # This should not fail the whole workflow run
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run codespell
      uses: codespell-project/actions-codespell@v1
