#Github Workflow to build with docker-compose
#
#SPDX-FileCopyrightText: 2023 Intevation GmbH
#SPDX-License-Identifier: AGPL-3.0-or-later

name: "Docker-Compose build pkg"

on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - '.github/**'

jobs:
  docker-pkg:
    name: Run docker-compose build pkg
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: create empty packages directory
      run: mkdir packages/
    - name: docker-compose build
      uses: sudo-bot/action-docker-compose@latest
      with:
        cli-args: -f docker-compose.yml -f docker-compose.pkg.yml build --parallel
